// Code generated by mockery v2.20.2. DO NOT EDIT.

package score

import (
	scoreApi "github.com/kneu-messenger-pigeon/score-api"
	mock "github.com/stretchr/testify/mock"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

// GetStudentDiscipline provides a mock function with given fields: studentId, disciplineId
func (_m *MockClientInterface) GetStudentDiscipline(studentId uint, disciplineId int) (scoreApi.DisciplineScoreResult, error) {
	ret := _m.Called(studentId, disciplineId)

	var r0 scoreApi.DisciplineScoreResult
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int) (scoreApi.DisciplineScoreResult, error)); ok {
		return rf(studentId, disciplineId)
	}
	if rf, ok := ret.Get(0).(func(uint, int) scoreApi.DisciplineScoreResult); ok {
		r0 = rf(studentId, disciplineId)
	} else {
		r0 = ret.Get(0).(scoreApi.DisciplineScoreResult)
	}

	if rf, ok := ret.Get(1).(func(uint, int) error); ok {
		r1 = rf(studentId, disciplineId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentDisciplines provides a mock function with given fields: studentId
func (_m *MockClientInterface) GetStudentDisciplines(studentId uint) (scoreApi.DisciplineScoreResults, error) {
	ret := _m.Called(studentId)

	var r0 scoreApi.DisciplineScoreResults
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (scoreApi.DisciplineScoreResults, error)); ok {
		return rf(studentId)
	}
	if rf, ok := ret.Get(0).(func(uint) scoreApi.DisciplineScoreResults); ok {
		r0 = rf(studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(scoreApi.DisciplineScoreResults)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockClientInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockClientInterface(t mockConstructorTestingTNewMockClientInterface) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
